// @(#)$Id$
//
// Evita Compiler - CastOperator.
//
// Copyright (C) 2010 by Project Vogue.
// Written by Yoshifumi "VOGUE" INOUE. (yosi@msn.com)

#if !defined(INCLUDE_evm_Compiler_Syntax_CastOperator_h)
#define INCLUDE_evm_Compiler_Syntax_CastOperator_h

#include "../Ir/Entity.h"

namespace Compiler {

// This class represents cast operator generated by CastLexer.
//  '(' type ')' expr => cast-operator expr
class CastOperator : public Entity_<CastOperator> {
  CASTABLE_CLASS(CastOperator);

  private: const Type* const type_;

  // ctor
  public: CastOperator(const Type& ty) : type_(&ty) {}

  // [G]
  public: const Type& GetTy() const { return *type_; }

  DISALLOW_COPY_AND_ASSIGN(CastOperator);
}; // CastOperator

} // Compiler

#endif // !defined(INCLUDE_evm_Compiler_Syntax_CastOperator_h)
