// -*- Mode: C++; -*-
// @(#)$Id$
//
// Evita Compiler - Names
//

DEFSYMBOL(add)
DEFSYMBOL(alias)
DEFSYMBOL(ascending)
DEFSYMBOL(descending)
DEFSYMBOL(dynamic)
DEFSYMBOL(from)
DEFSYMBOL(get)
DEFSYMBOL(global)
DEFSYMBOL(group)
DEFSYMBOL(into)
DEFSYMBOL(join)
DEFSYMBOL(let)
DEFSYMBOL(orderby)
DEFSYMBOL(partial)
DEFSYMBOL(remove)
DEFSYMBOL(select)
DEFSYMBOL(set)
DEFSYMBOL(value)
DEFSYMBOL(var)
DEFSYMBOL(where)
DEFSYMBOL(yield)

#undef DEFSYMBOL
